# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Akeem Piggott
title: Program Developer
email: akeempiggott@gmail.com
website: https://github.com/prince-akeem

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  princeakeem
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: prince_a_akeem
linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Akeem and I'm a Program Developer. I also have experience making software, web apps and multipler game servers. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Rails</mark>, <mark>C++</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/prince-akeem
        # link_text: Project Website
        additional_links:
          - title:  Rails secret application
            icon: fab fa-github
            url: github.com/prince-akeem
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Rails</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amazon.com
        link: Amazon.com
        # link_text: boringcompany.com
        sub_title: ICQA Program Developer
        caption: Augest 2022 - Present
        quote: > 
          We've had three big ideas at Amazon that we've stuck with for 18 years, and thy're the reason we're successful: Put the customer first. Invent. And be patient.(Jeff Bezos)
        description: | # this will include new lines to allow paragraphs
            Most modern company needs developers and Amazon is no exception. Amazon was founded on july 5, 1944 and has evoled from just an e-commerce or retailer, Amazon is multinational technology company that offers everything from A to Z.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Norco College
        caption: 2019 - 2023
        sub_title: Associates in Computer Science
        quote: >
          Norco College is a two-year public institution of higher education, one of three colleges in the Riverside Community College District (RCCD). Established as a campus of the RCCD in 1991, Norco College was granted Initial Accreditation by the Accrediting Commission for Community and Junior Colleges (ACCJC) in January of 2010 and is the 112th independent college of the California Community College system.
        description: | # this will include new lines to allow paragraphs
          During my time at Norco College I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as college and learnt a lot about a healthy work life balance.

          I spent some of my free time helping other students that was struggling in the class by hosting review sessions in the library or over discord video calls.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Soccer
      - Gaming
      - Painting
      - [Live to the fullest](https://www.youtube.com/watch?v=2S0QhGGO1gQ)

      Look at this cool image  
      ![Cool](https://thumbs.dreamstime.com/z/cool-word-car-frost-28138481.jpg "Cool")
      ![Java Cred](https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/67932561)
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
